services:
  # --- FRONTEND (Static Site) ---
  - type: web
    name: webxr-frontend
    env: static
    staticPublishPath: frontend
    buildCommand: ""
    autoDeploy: true
    pullRequestPreviewsEnabled: false

  # --- BACKEND (Python / Flask API) ---
  - type: web
    name: webxr-backend
    env: python
    buildCommand: ""
    startCommand: "python backend/server/server.py"
    autoDeploy: true
