version: "1"

services:
  # === Frontend: static site ===
  - name: webxr-frontend
    type: static_site
    envVars: []
    buildCommand: ""
    publishPath: frontend
    autoDeploy: true

  # === Backend: Flask server ===
  - name: webxr-backend
    type: web_service
    runtime: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: python backend/server/server.py
    autoDeploy: true
