services:
  # --- FRONTEND (Static) ---
  - type: web
    name: webxr-frontend
    env: static
    staticPublishPath: frontend
    buildCommand: ""
    plan: free
    autoDeploy: true
    pullRequestPreviewsEnabled: false

  # --- BACKEND (Python / Flask) ---
  - type: web
    name: webxr-backend
    env: python
    buildCommand: ""
    startCommand: "python backend/server/server.py"
    plan: free
    autoDeploy: true
